=== albertdwtg/gcp_object_checker/cloud_function_code/payload_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "job_owner": {
            "type": "string",
            "pattern": "^[^0-9]*$",
            "minLength": 2,
            "maxLength": 100
        },
        "creation_date": {
            "type": "string",
            "format": "date",
            "pattern": "^[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$"
        },
        "job_type": {
            "type": "string",
            "enum": ["UNIQUE", "MULTIPLE", "PIPELINE"]
        },
        "target_cloud_run": {
            "type": "string"
        },
        "variables": {
            "type": "object"
        },
        "parallel_param": {
            "type": "string"
        },
        "parallel_min": {
            "type": "number"
        },
        "parallel_max": {
            "type": "number"
        },
        "parallel_increment": {
            "type": "number"
        },
        "parallel_type": {
            "type": "string",
            "enum": ["NUMERIC", "LIST", "DATE"]
        },
        "steps": {
            "type": "array",
            "items": {
                "type": "object"
            },
            "minItems": 1
        }
        
    },
    "required": ["job_owner", "creation_date", "job_type", "target_cloud_run"],
    "additionalProperties": false
}

=== albertdwtg/gcp_object_checker/scheduler_payloads/payload_1.json
{
    "job_owner": "Albert",
    "creation_date": "2024-05-08",
    "job_type": "UNIQUE",
    "target_cloud_run": "first-job", 
    "variables" : {
        "project_id": "model-zoo-382809",
        "dataset_id": "raw_data_air_quality",
        "report_type": "CATCHUP",
        "start_time": "2023-05-25",
        "end_time": "2024-05-25"
    }
}
